#!/bin/python3

import argparse
from datetime import datetime
from os import listdir
from os.path import join

def process_file(path, field_names):
    f = open(path, 'r')

    field_indices = {}
    out_line = ''
    for line in f:
        line = line.rstrip() # remove trailing newline character
        array = line.split(",")

        if line.startswith('ZZZZ,'):
            # if 'out_line' has information
            if out_line:
                print(out_line)

            # parse timestamp and add to out_line
            utc_time = datetime.strptime(array[3] + "T" + array[2], \
                "%d-%b-%YT%H:%M:%S")
            epoch_time = (utc_time - datetime(1970, 1, 1)).total_seconds()
            out_line=str(epoch_time)
        elif not out_line:
            # before first record is reported
            # TODO - comment
            if array[0] in field_names:
                indices = []
                field_indices[array[0]] = indices

                # iterate over field names
                for field_name in field_names[array[0]]:
                    for i, j in enumerate(array):
                        if field_name == j:
                            indices.append(i)
        else:
            if array[0] in field_indices:
                for index in field_indices[array[0]]:
                    out_line+="," + array[index]

if __name__ == '__main__':
    # parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('inputdir', metavar='IN_DIR',
        help='TODO - description')
    parser.add_argument('outputdir', metavar='OUT_DIR',
        help='TODO - description')
    parser.add_argument('fields', metavar='F', nargs='+',
        help='TODO - description')
    args = parser.parse_args()

    # parse field names
    field_names={}
    for field in args.fields:
        array=field.split(':')

        if array[0] in field_names:
            field_names[array[0]].append(array[1])
        else:
            field_names[array[0]] = [array[1]]

    # iterate over all files in INDIR
    for filename in listdir(args.inputdir):
        # process file
        print(filename)

        process_file(join(args.inputdir, filename), field_names)
