#!/usr/bin/env bash

# necessary to print gpg cli password auth in new window
GPG_TTY=$(tty)
export GPG_TTY

password_keys=$(veil list-keys)
if [ "${#password_keys}" -eq "0" ]; then
  echo "failed to retrieve passwords"
  sleep 1s
  exit 1
fi

password_files=( "$password_keys" )
password=$(printf '%s\n' "${password_files[@]}" | fzf)

if [ -n "$password" ]; then
  IFS=":" read -r group key <<< "$password"
  veil clip "$group" "$key"
fi
