#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

password_files=( "$(veil list-keys)" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    IFS=":" read -r group key <<< "$password"
    #echo "$group $key" | xclip -selection clipboard
    veil clip "$group" "$key"

	#pass show -c "$password" 2>/dev/null
else
    IFS=":" read -r group key <<< "$password"
    #echo "$group $key" | xclip -selection clipboard
    veil clip "$group" "$key"

	#pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
